# ============================================================
# schemas.py — Pydantic models for API request/response validation
# ============================================================
# When someone sends data to our API (like adding a new database),
# we need to validate that data:
# - Is the host field provided?
# - Is the port a valid number?
# - Did they include all required fields?
#
# Pydantic does this automatically. We define what the data should
# look like, and Pydantic rejects anything that doesn't match.
#
# SQLAlchemy models = database tables (how data is STORED)
# Pydantic schemas = API contracts (how data is SENT and RECEIVED)
# ============================================================

from pydantic import BaseModel, Field  # Base class for all Pydantic models
from typing import Optional     # For fields that can be None
from datetime import datetime


# --- Data Source Schemas ---

class DataSourceCreate(BaseModel):
    """
    What the user sends when connecting a new database.
    
    This is the REQUEST body. When someone calls:
    POST /api/data-sources
    with JSON like {"name": "Production", "host": "localhost", ...}
    
    Pydantic validates that all required fields are present
    and rejects the request if anything is missing.
    """
    name: str                          # Required: friendly name
    host: str                          # Required: database host
    port: str = "5432"                 # Optional: defaults to 5432
    database_name: str                 # Required: database name
    username: str                      # Required: database user
    password: str                      # Required: database password
    db_type: str = "postgresql"  # postgresql or mysql

class DataSourceResponse(BaseModel):
    """
    What we send back to the user after they add a database.
    
    This is the RESPONSE body. Notice it includes 'id' and 'created_at'
    which are generated by the server — the user doesn't send these.
    
    Also notice password is NOT included — we never send passwords back.
    """
    id: int
    name: str
    host: str
    port: str
    database_name: str
    username: str
    db_type: str
    is_active: bool
    last_connected: Optional[datetime] = None
    created_at: datetime

    class Config:
        from_attributes = True  # Allows creating from SQLAlchemy model objects


# --- Monitoring Rule Schemas ---

class RuleCreate(BaseModel):
    """
    What the user sends when creating a new monitoring rule.
    
    Example JSON:
    {
        "data_source_id": 1,
        "table_name": "orders",
        "column_name": "amount",
        "check_type": "range_check",
        "min_value": "0",
        "max_value": "50000",
        "severity": "critical"
    }
    """
    data_source_id: int
    table_name: str
    column_name: Optional[str] = None  # Null for table-level checks
    check_type: str                     # null_check, range_check, etc.
    min_value: Optional[str] = None
    max_value: Optional[str] = None
    custom_sql: Optional[str] = None
    severity: str = "warning"


class RuleResponse(BaseModel):
    id: int
    data_source_id: int
    table_name: str
    column_name: Optional[str]
    check_type: str
    min_value: Optional[str]
    max_value: Optional[str]
    custom_sql: Optional[str]
    severity: str
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True


# --- Check Result Schemas ---

class CheckResultResponse(BaseModel):
    id: int
    data_source_id: int
    rule_id: int
    table_name: str
    column_name: Optional[str]
    check_type: str
    passed: bool
    actual_value: Optional[str]
    expected_value: Optional[str]
    message: Optional[str]
    score: float
    checked_at: datetime

    class Config:
        from_attributes = True


# --- Chat Schemas ---

class ChatRequest(BaseModel):
    """
    What the user sends when asking a question in the chat module.
    
    Example: {"data_source_id": 1, "message": "How many orders were placed last month?"}
    """
    data_source_id: int
    message: str


class ChatResponse(BaseModel):
    user_message: str
    generated_sql: Optional[str]
    ai_response: str
    query_success: bool
    created_at: datetime
    columns: Optional[list] = None
    rows: Optional[list] = None
    chart_config: Optional[dict] = None

    class Config:
        from_attributes = True

# --- Health Score Schema ---

class TableHealthResponse(BaseModel):
    """Response showing health score for a single table."""
    table_name: str
    score: float              # 0-100
    total_checks: int
    passed_checks: int
    failed_checks: int
    last_checked: Optional[datetime]


class OverallHealthResponse(BaseModel):
    """Response showing overall health across all monitored tables."""
    overall_score: float
    total_tables: int
    healthy_tables: int       # Score >= 80
    warning_tables: int       # Score 50-79
    critical_tables: int      # Score < 50
    tables: list[TableHealthResponse]


class MaskingRuleCreate(BaseModel):
    """Create a new masking rule for a sensitive column."""
    data_source_id: int
    table_name: str
    column_name: str
    mask_type: str  # email, phone, address, name, credit_card, ssn, full, custom
    visible_start: int = 0
    visible_end: int = 0


class MaskingRuleResponse(BaseModel):
    id: int
    data_source_id: int
    table_name: str
    column_name: str
    mask_type: str
    visible_start: int
    visible_end: int
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True

class UserCreate(BaseModel):
    """For signup."""
    email: str
    username: str
    password: str = Field(..., min_length=8, max_length=72)


class UserResponse(BaseModel):
    id: int
    email: str
    username: str
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True


class Token(BaseModel):
    """JWT token response."""
    access_token: str
    token_type: str = "bearer"
    user: UserResponse